name = "PartitionedPoisson"
uuid = "dd027654-807b-4d31-8f1a-ffac5c59a6b5"
authors = ["Francesc Verdugo <fverdugo@cimne.upc.edu>"]
version = "0.1.0"

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Gridap = "56d4f2e9-7ea1-5844-9cf6-b9c51ca7ce8e"
GridapPETSc = "bcdc36c2-0c3e-11ea-095a-c9dadae499f1"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
PartitionedArrays = "5a9dfac6-5c52-46f7-8278-5e2210713be9"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
BSON = "0.2"
FileIO = "1.4"
Gridap = "0.16"
IterativeSolvers = "0.9"
MPI = "0.16"
PackageCompiler = "1.2"
PartitionedArrays = "0.2"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
